name: drupal8
recipe: drupal8
config:
  webroot: web
  php: '7.2'
  via: nginx
  database: mariadb:10.3
  conf:
    server: config/nginx.conf
    php: config/php.ini
services:
  appserver:
    # Add a Build Step to your App.
    run:
      - "cd $LANDO_MOUNT && composer install"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node:6.10
    globals:
      gulp-cli: "latest"
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
